### ISSUE TITLE
Maven repo link broken on readme page.

### ISSUE THREAD

**Issue by levsa** [l0rdn1kk0n/wicket-requirejs#7]
Maven repo link on the readme page is broken (and old, doesn't point to latest version).

**Comment by martin-g** [comment]
Thank you!

**Comment by martin-g** [comment]
I've just updated the project dependencies and released 0.1.2.

**Comment by levsa** [comment]
Thanks for the quick response! 

Btw, is the example on the readme page up to date. There were some differences with the demo code in the test directory. Also, is there a way to run the demo code easily?

**Comment by martin-g** [comment]
The easiest way to run the demo is to start https://github.com/l0rdn1kk0n/wicket-requirejs/blob/master/src/test/java/de/agilecoders/wicket/demo/Start.java as a normal Java application, i.e. a class with a main() method, in your IDE.
It will start Jetty in embedded mode. Just navigate to http://localhost:8080 and play with it.
Please send a Pull Request if the README is outdated or wrong.
Thanks!
